name: Auto Build

on:
  push:
    branches:
      - master
    tags:
      - '*'
#  pull_request:
  workflow_dispatch:
    inputs:

env:
  IMAGE_NAME: ehforwarderbot-plus-docker

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@v8
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}